#!/bin/bash

set -e

# Reimplements a standard C function that may not
# exist on MacOS if the markers are using it.
realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

SCRIPT_DIR="$( cd "$(dirname "$0")" ; pwd -P )"
JAR_FILE="$SCRIPT_DIR/build/libs/csc435-compiler.jar"

if test ! -f "$JAR_FILE"; then
    echo "Jar not found at \"$JAR_FILE\""
    echo "Recompiling"
    ( cd "$SCRIPT_DIR" ; make build )
else
    echo "Using existing jar without recompile"
fi

java -jar "$JAR_FILE" "$@"
